### ISSUE TITLE
iup.Open() fails with error after package installation on Linux Mint 20.3 Cinnamon

### ISSUE THREAD

**Issue by rasteric** [gen2brain/iup-go#1]
The error might be GTK-related: `Pango-ERROR **: 10:17:40.740: Harfbuzz version too old (1.3.2)`

I tried to follow the (vaguely) related instructions here: 

https://unix.stackexchange.com/questions/589993/pango-error-harfbuzz-version-too-old

and here:

https://github.com/GGBRW/BOOLR/issues/45

Unfortunately, so far I didn't get it to work. Is there a way to force recompilation of IUP with these libraries or any other way to fix this except for system-wide downgrading of Pango libraries?

**Comment by gen2brain** [comment]
I did try to build in Ubuntu 20.4 and that worked fine after the dev package is installed, the screenshot is taken there. I thought Mint is Ubuntu-based?

**Comment by rasteric** [comment]
Yes, Mint is ubuntu-based, Mint 20.3 should be based on Ubuntu Focal. Here is the output:

```
> pkg-config --cflags --libs gtk+-3.0 gdk-3.0 

-pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/atk-1.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgtk-3 -latk-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 
```
The error looks like this: 

```
giuprj:48681): Pango-ERROR **: 10:45:42.067: Harfbuzz version too old (1.3.2) 
 SIGTRAP: trace trap PC=0x7f86536f7295 m=5 sigcode=128 signal arrived during cgo execution 
 goroutine 7 [syscall]: runtime.cgocall(0x8f8990, 0xc000068f68) 	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000068f40 sp=0xc000068f08 pc=0x4db55c github.com/gen2brain/iup-go/iup._Cfunc_IupOpen(0x0, 0x0) 	_cgo_gotypes.go:2392 +0x4c fp=0xc000068f68 sp=0xc000068f40 pc=0x6cfeec github.com/gen2brain/iup-go/iup.Open(...) 	/home/nemo/go/pkg/mod/github.com/gen2brain/iup-go/iup@v0.0.0-20220530155049-dfde5aeec039/bind_iup.go:18 main.run() 	/home/nemo/go/src/github.com/rasteric/giuprj/main.go:33 +0x33 fp=0xc000068fb0 sp=0xc000068f68 pc=0x8f2173 golang.design/x/mainthread.Init.func1() 
```
I'm not sure I can downgrade Pango system-wide, as is suggested in other solutions to similar problems (with Harfbuzz version 1.3.1). I've tried copying older dynamic Pango libraries into the executable directory, as described in one of the links, but this didn't help. Are they compiled statically? Or maybe I did something wrong or downloaded the wrong .so libraries.

Compiling with gtk2 tag does not help - it yields the same error.

**Comment by gen2brain** [comment]
It seems like nothing to do with this repo. What is expected from pkg-config is to return a valid combination for GTK+ linking. Usually, they are dynamic libraries, but you can edit pkg-config files as you want, to i.e. include /path/to/libpango.a if you want, as long as that is a valid combination without conflicts. 

Looks like that is a clear system/gtk error. It is strange that you didn't have problems with other apps, or is that a specific example you are trying that maybe triggers that path in code, like a font example? Alarm example, or getfile doesn't even have mainloop, any difference with those?

Sorry, I cannot be of much help here, as I said it is not issue with bindings, there is nothing I can change there. I would not advise to change system libraries, but anyway it is broken so it cannot do much harm I guess.

**Comment by gen2brain** [comment]
Anyway, if you are going to mess with libraries, I suggest upgrading Harfbuzz, not downgrading Pango.

**Comment by gen2brain** [comment]
Just to add for reference, I have on my system harfbuz version 3.40, Ubuntu 20.4 has version 2.6.4, yours is 1.3.2, yikes, something is not right.

**Comment by rasteric** [comment]
I have investigated this further for many hours and am giving up. Even when I put newer versions of _libharfbuzz_ into the same folder as the executable and start it with `LD_LIBRARY_PATH=/absolute/path/to/lib/folder ./executable` it will complain about having an old version of Harfbuzz (1.3.2). When I put older versions of all pango libraries (from Ubuntu Bionic) into the folder and start in the same way, it complains `symbol lookup error: /lib/x86_64-linux-gnu/libgtk-3.so.0: undefined symbol: pango_font_description_set_variations `, so these versions are too old.

**Comment by gen2brain** [comment]
No idea, sorry. I was thinking that you have something in /usr/local and similar but it looks like you checked everything. The library is tested in Fedora, Ubuntu, and even old Centos with gtk2, and Gentoo, and it just works.
