### ISSUE TITLE
Hide Handle in CLOSE_CB

### ISSUE THREAD

**Issue by lthon09** [gen2brain/iup-go#10]
I've implemented a traybar item, now I want the window to not close when the close button on the titlebar gets clicked. This is what I've tried:

```go
func closeHandler(_ iup.Ihandle) int {
	iup.Hide(iup.GetHandle("window"))

	return iup.IGNORE
}

window.SetCallback("CLOSE_CB", iup.CloseFunc(closeHandler))
```

However, calling `Hide()` seems to close the window, if I remove that line, it works fine. I've tried setting the handle's `VISIBLE` attribute as well and it doesn't give a different result.

Any ideas? Thanks in advance!

**Comment by lthon09** [comment]
I figured out calling `Hide()` closes the window, no idea if it's possible to hide it without closing it.

**Comment by gen2brain** [comment]
@lthon09 Please, search the IUP mailing list or ask questions there, issues are, well, for issues.

**Comment by lthon09** [comment]
Okay, thanks.

**Comment by lthon09** [comment]
For anyone reading through this, I've now only discovered that the last dialog must be visible in order for the mainloop to continue.

**Comment by lthon09** [comment]
To achieve this, you can set the `LOCKLOOP` global attribute before hiding the window, as stated here: https://www.tecgraf.puc-rio.br/iup/en/attrib/iup_globals.html#lockloop
