### ISSUE TITLE
Global TXTHLCOLOR returns TXTBGCOLOR on Linux/GTK

### ISSUE THREAD

**Issue by rasteric** [gen2brain/iup-go#14]
I'm drawing a custom control in a canvas, and there seems to be no way to obtain the correct highlight color (for filled highlight rectangles) on Linux in GTK.  Observations:

1. `iup.DrawSelectRect` draws a rectangle in the wrong color - some custom dark blue on my machine, not the lighter blue used with by the GTK themes I'm running and testing with. This color doesn't seem to be part of the GTK theme, it appears to be hard-coded.
2. `iup.GetGlobal("TXTHLCOLOR")` returns the background color of text fields, i.e., white on a standard light theme, dark grey on a test GTK theme I'm using. It's exactly the color of text entry fields.
3. Selections in flat controls like `FlatList` also use the wrong selection colors, some white or grey text background color. 

Neither of these colors are the same as what an `iup.List()` uses for selections. I cannot find a way to get the theme-provided highlight color. I can also not get the DrawSelectRect color.

I'm not sure whether this is an IUP problem or has to do with the Go wrapper. I can provide screenshots if needed.

**Comment by gen2brain** [comment]
Sorry, no idea, these are just bindings. You should direct your question to the IUP mailing list, of guys that wrote that code.

**Comment by gen2brain** [comment]
I didn't mean to close right now, maybe someone has something to say, but nothing will happen here basically if there is an issue here it is on the IUP side.

**Comment by rasteric** [comment]
Nah, feel free to close it. I thought that it's a general IUP issue, just wanted to make sure it's not something in the wrapper.
