### ISSUE TITLE
IupGetParam() ?

### ISSUE THREAD

**Issue by agambier** [gen2brain/iup-go#15]
Hello,

Is it planned to integrate support for `IupGetParam()` or is it too complicated ?

Thanks

**Comment by gen2brain** [comment]
No, there are no plans to add that.

**Comment by agambier** [comment]
because of lack of time of technical issue ?

**Comment by gen2brain** [comment]
I tried a couple of times to add GetParam and I failed. Any function that accepts a callback would be problematic, callbacks are complex enough already. If anyone succeeds PR is welcome of course, but I will not spend more time on this. It does look useful, but all that can be done manually anyway.

**Comment by agambier** [comment]
I've started to test to add GetParam. I'm able to show the dialog with a few param but I don't have a lot of spare time to do it.
I don't know if I'll be able to fully implement it but it is worth it to try.

I'll keep you updated
