### ISSUE TITLE
Can I use it for production?

### ISSUE THREAD

**Issue by 0x457** [gen2brain/iup-go#16]
Can I use it for production?

**Comment by gen2brain** [comment]
@0x457 Sure, IUP is developed and used for many years, and there are still many very complex UI apps that use IUP and are maintained. You just need to follow the documentation, but that is the same for every UI toolkit. The new release is expected to happen soon, with some bug fixes. Go bindings however do not include support for any additional controls, just core.

I wish development is faster though, i.e. I would like to see legacy systray in Linux be replaced with a modern one, table/list view is also on TODO list, etc. but I cannot help with that. Perhaps moving out to GitHub would be beneficial for the IUP project, I didn't see a discussion about that, maybe they have some reasons, or they just don't have the time.
