### ISSUE TITLE
Compile fails with "gl" tag:  undefined: pih

### ISSUE THREAD

**Issue by justinfx** [gen2brain/iup-go#3]
I was trying to build some of the examples on an Ubuntu linux distro, using `-tags gl`, and the compile failed with missing references:

```
# github.com/gen2brain/iup-go/iup
../iup/bind_gl.go:38:21: undefined: pih
../iup/bind_gl.go:45:30: undefined: pih
../iup/bind_gl.go:52:21: undefined: pih
../iup/bind_gl.go:59:17: undefined: pih
../iup/bind_gl.go:67:17: undefined: pih
../iup/bind_gl.go:83:33: undefined: pih
```

Are these refs supposed to be `C.pih`?
https://github.com/gen2brain/iup-go/blob/iup/v3.30.3/iup/bind_gl.go#L38

**Comment by gen2brain** [comment]
That function is removed, it should be fixed in https://github.com/gen2brain/iup-go/commit/9bc1f88eb0dea75f745660ff958517ee97122af6

**Comment by justinfx** [comment]
Yep, I didn't think I needed the `gl` tag in most cases. Was just letting you know it was broken :-) Thanks for fixing it.

**Comment by gen2brain** [comment]
I added all build test cases in Github actions. At least it will catch such regressions in the future. Thanks!
